project_id = "oiritkkxlvwhuvppteyi"

[functions.ndc-lookup]
verify_jwt = false

[functions.send-caregiver-alert]
verify_jwt = false

[functions.check-missed-doses]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
